load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "callshow_lib",
    srcs = glob(["**/*.py"]),
    imports = [".."],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "callshow",
    srcs = ["cli.py"],
    main = "cli.py",
    imports = [".."],
    deps = [":callshow_lib"],
    visibility = ["//visibility:public"],
)
